apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqs-consumer
  annotations:
    iam.amazonaws.com/role: k8s-pod-sqs-consume
spec:
  selector:
    matchLabels:
      app: sqs-consumer
  template:
    metadata:
      labels:
        app: sqs-consumer
    spec:
      containers:
      - name: sqs-consumer
        image: chankh/sqs-consumer-sample
        env:
          - name: AWS_REGION
            value: us-west-2
